import { Bar, CartItem, Line, Order, Pie, Product, ShippingInfo, Stats, User } from "./types";

export type CustomeError = {
    status: number,
    data: {
        message: string,
        success: boolean
    }
};

export type MessageResponse = {
    success: boolean,
    message: string
};

export type AllUserResponse = {
    success: boolean,
    users: User[]
}

export type UserResponse = {
    success: boolean,
    user: User
};

export type AllProductsResponse = {
    success: boolean,
    products: Product[]
};

export type AllCategoriesResponse = {
    success: boolean,
    categories: string[]
};

export type SearchProductsResponse = AllProductsResponse & {
    totalPage: number
};

export type SearchProductsRequest = {
    search: string,
    sort: string,
    category: string,
    page: number,
    price: number
};

export type NewProductRequest = {
    id: string,
    formData: FormData
};

export type UpdateProductRequest = {
    userId: string,
    productId: string,
    formData: FormData
};

export type DeleteProductRequest = {
    userId: string,
    productId: string,
};

export type ProductResponse = {
    success: boolean,
    product: Product
};

export type DeleteUserRequest = {
    userId: string,
    adminUserId: string,
};

export type newOrderRequest = {
    shippingInfo: ShippingInfo,
    orderItems: CartItem[], // we will be sending cartItem and not OrderItem because in OrderItem, we have a special id which is generated by mongodb, but there is no way to pass id of the order.
    subTotal: number,
    tax: number,
    shippingCharges: number,
    discount: number,   
    total: number,   
    user: string
};

export type StatsResponse = {
    success: boolean,
    stats: Stats
}

export type PieResponse = {
    success: boolean,
    charts: Pie
}

export type BarResponse = {
    success: boolean,
    charts: Bar
}

export type LineResponse = {
    success: boolean,
    chart: Line
}

export type updateOrderRequest = { 
    userId: string,
    orderId: string
};

export type AllOrdersResponse = {
    success: boolean,
    orders: Order[]
};

export type OrderDetailsResponse = {
    success: boolean,
    order: Order
};
